project:
  type: website

website:
  title: "Justyn"
  repo-url: "https://github.com/becausejustyn/blog"
  description: "This is my personal blog."
  navbar:
    title: false
    background: primary
    search: true
    left:
      - text: "{{< fa house-user >}} Home"
        href: index.qmd
      - text: "{{< fa newspaper >}} Blog"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/becausejustyn
      - icon: twitter
        href: https://twitter.com/becausejustyn
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@becausejustyn"
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]



