project:
  type: website

website:
  title: "Justyn"
  description: "This is my personal blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/becausejustyn
      - icon: twitter
        href: https://twitter.com/becausejustyn
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@becausejustyn"
format:
  html:
    theme: cosmo
    css: styles.css



